services:
  rag-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag-service
    ports:
      - "8000:8000"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBED_MODEL=${EMBED_MODEL:-amazon.titan-embed-text-v2:0}
      - QDRANT_URL=${QDRANT_URL:-http://qdrant:6333}
      - AUTH_TOKEN=${AUTH_TOKEN}
      - HF_TOKEN=${HF_TOKEN}

      - HF_HOME=/data/hf_cache
      - TRANSFORMERS_CACHE=/data/hf_cache
      - HUGGINGFACE_HUB_CACHE=/data/hf_cache

    restart: unless-stopped
    depends_on:
      - qdrant
    volumes:
      - ./logs:/app/logs
      - hf_cache:/data/hf_cache

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage 


  streamlit-ui:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: streamlit-ui
    ports:
      - "8501:8501"
    depends_on:
      - rag-service
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
      - RAG_API_URL=http://rag-service:8000
    restart: unless-stopped

volumes:
  hf_cache:
  qdrant_data:

